version: "3"

services:
  redis:
      container_name: redis
      image: redis:alpine3.8
      ports:
        - '127.0.0.1:6379:6379'
      volumes:
        - 'redis_data:/data'
      restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - .:/code
    command: python3 ml/manage.py runserver 0.0.0.0:8000
    depends_on: 
      - redis
      
volumes:
  redis_data: